project: #项目信息
 name: tx-demo-client
 server:
   transaction: tx-demo-server
   client2: tx-demo-client2
   client3: tx-demo-client3
 server-url:
   transaction: http://localhost:8937
   client2: http://localhost:8938
   client3: http://localhost:8939
    
server.port: 8936
 
spring: #应用配置
  application:
    name: ${project.name} 
  data:
    cassandra:
      keyspace-name: sgp_tx
      contactPoints: 127.0.0.1
      port: 9042
    
feign:
  hystrix:
    enabled: true   
    
message: #消息服务
  model: ROCKET_MQ
  rocketmq:
    namesrvAddr: localhost:9876 
    
#master: #主数据库配置
# db:
#  type: mysql
#  url: jdbc:mysql://192.168.10.73:3306/sgp_tx?useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&serverTimezone=Asia/Shanghai
#  username: root
#  password: hbasesoft.com

#cache: #缓存配置
#  model: SIMPLE